trigger:
- main

pool:
  name: Default

variables:
- group: dockerhub-secrets

- name: dockerHubUser
  value: bsrivathsa

- name: frontendImage
  value: react-frontend

- name: backendImage
  value: springboot-backend


stages:

# BUILD AND PUSH

- stage: BuildAndPush
  displayName: Build and Push Docker Images
  jobs:
  - job: BuildPushImages
    steps:

    - checkout: self

    - script: |
        echo "Logging into DockerHub..."
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(dockerHubUser)" --password-stdin
      displayName: DockerHub Login

    - script: |
        echo "Building frontend image..."
        docker build -t $(dockerHubUser)/$(frontendImage):$(Build.BuildId) ./full-stack/react-js-frontend
      displayName: Build Frontend Image

    - script: |
        echo "Building backend image..."
        docker build -t $(dockerHubUser)/$(backendImage):$(Build.BuildId) ./full-stack/spring-boot-backend
      displayName: Build Backend Image

    - script: |
        echo "Pushing frontend image..."
        docker push $(dockerHubUser)/$(frontendImage):$(Build.BuildId)
      displayName: Push Frontend Image

    - script: |
        echo "Pushing backend image..."
        docker push $(dockerHubUser)/$(backendImage):$(Build.BuildId)
      displayName: Push Backend Image

# DEPLOY

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAKS
    steps:

    - task: Kubernetes@1
      displayName: Login to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aks-service-connection'
        azureResourceGroup: 'demo-group'
        kubernetesCluster: 'new-aks-demo'

    - script: |
        echo "Updating frontend deployment..."
        kubectl set image deployment/frontend-deployment \
        frontend=$(dockerHubUser)/$(frontendImage):$(Build.BuildId)

        echo "Updating backend deployment..."
        kubectl set image deployment/backend-deployment \
        backend=$(dockerHubUser)/$(backendImage):$(Build.BuildId)
      displayName: Update AKS Deployments

    - script: |
        echo "Waiting for rollout to complete..."
        kubectl rollout status deployment/frontend-deployment
        kubectl rollout status deployment/backend-deployment
      displayName: Verify Deployment Rollout