trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: dockerhub-secrets

- name: dockerHubUser
  value: bsrivathsa

- name: frontendImage
  value: react-frontend

- name: backendImage
  value: springboot-backend

stages:

- stage: Build
  displayName: Build Docker Images
  jobs:
  - job: BuildImages
    displayName: Build Frontend and Backend
    steps:

    - checkout: self

    - script: |
        docker build -t $(dockerHubUser)/$(frontendImage):$(Build.BuildId) ./full-stack/react-js-frontend
      displayName: Build Frontend Image

    - script: |
        docker build -t $(dockerHubUser)/$(backendImage):$(Build.BuildId) ./full-stack/spring-boot-backend
      displayName: Build Backend Image


- stage: Push
  displayName: Push Images to DockerHub
  dependsOn: Build
  jobs:
  - job: PushImages
    displayName: Push Docker Images
    steps:

    - checkout: self

    - script: |
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(dockerHubUser)" --password-stdin
      displayName: DockerHub Login

    - script: |
        docker push $(dockerHubUser)/$(frontendImage):$(Build.BuildId)
      displayName: Push Frontend Image

    - script: |
        docker push $(dockerHubUser)/$(backendImage):$(Build.BuildId)
      displayName: Push Backend Image


- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Push
  jobs:
  - job: DeployToAKS
    displayName: Update Kubernetes Deployments
    steps:
    - task: Kubernetes@1
      displayName: Login to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'aks-service-connection'
        azureResourceGroup: 'demo-cluster_group'
        kubernetesCluster: 'demo-cluster'

    - script: |
        kubectl set image deployment/frontend-deployment \
        frontend=$(dockerHubUser)/$(frontendImage):$(Build.BuildId) 

        kubectl set image deployment/backend-deployment \
        backend=$(dockerHubUser)/$(backendImage):$(Build.BuildId)
      displayName: Update AKS Deployments

    - script: |
        echo "Waiting for rollout to complete..."

        kubectl rollout status deployment/frontend-deployment
        kubectl rollout status deployment/backend-deployment
      displayName: Verify Deployment Rollout